syntax = "proto3";

package liveedit.v1;

option go_package = "proto/document;documentpb";

import "google/protobuf/empty.proto";

// import "validate/validate.proto";
// import "google/api/annotations.proto";
// import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "LiveEdit"
    version: "1.0"
    description: "LiveEdit API"
  }
  security_definitions: {
    security: {
      key: "Bearer"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
      }
    }
  }
  security: {
    security_requirement: {
      key: "Bearer"
      value: {}
    }
  }
};

// Роли пользователя
enum Role {
  ROLE_UNSPECIFIED = 0;
  OWNER = 1;
  EDITOR = 2;
  VIEWER = 3;
}

// ========================
// Запросы / Ответы
// ========================

message CreateDocumentRequest {
  string title = 1 [(validate.rules).string = {min_len: 1, max_len: 255}];
  string content = 2;
}

message CreateDocumentResponse {
  uint64 id = 1;
}

message GetDocumentsRequest {}

message DocumentItem {
  uint64 id = 1;
  string title = 2;
  string created_at = 3;
  string updated_at = 4;
  Role role = 5;
}

message GetDocumentsResponse {
  repeated DocumentItem documents = 1;
}

message GetDocumentRequest {
  uint64 id = 1 [(validate.rules).uint64 = {gt: 0}];
}

message GetDocumentResponse {
  uint64 id = 1;
  string title = 2;
  string content = 3;
  Role role = 4;
  string created_at = 5;
  string updated_at = 6;
}

message DeleteDocumentRequest {
  uint64 id = 1 [(validate.rules).uint64.gt = 0];
}


message SetUserRoleRequest {
  uint64 document_id = 1 [(validate.rules).uint64.gt = 0];
  uint64 user_id = 2 [(validate.rules).uint64.gt = 0];
  Role role = 3 [(validate.rules).enum = {in: [2, 3]}];
}

message RevokeAccessRequest {
  uint64 document_id = 1 [(validate.rules).uint64.gt = 0];
  uint64 user_id = 2 [(validate.rules).uint64.gt = 0];
}

message UpdateDocumentRequest {
  uint64 document_id = 1 [(validate.rules).uint64 = {gt: 0}];
  string title = 2 [(validate.rules).string = {min_len: 1, max_len: 255}];
  string content = 3;
}

message UpdateDocumentResponse {
  string updated_at = 1;
}

message CreateInviteLinkRequest {
  uint64 document_id = 1 [(validate.rules).uint64.gt = 0];
  Role role = 2 [(validate.rules).enum = {in: [2, 3]}]; // Только EDITOR или VIEWER
  string expires_at = 3; // Опционально, RFC3339
}

message CreateInviteLinkResponse {
  string invite_token = 1;
}

message AcceptInviteRequest {
  string invite_token = 1 [(validate.rules).string.min_len = 1];
}

// ========================
// Сервис
// ========================

service DocumentService {
  rpc CreateDocument(CreateDocumentRequest) returns (CreateDocumentResponse) {
    option (google.api.http) = {
      post: "/api/document"
      body: "*"
    };
  }
  rpc GetDocuments(GetDocumentsRequest) returns (GetDocumentsResponse) {
    option (google.api.http) = {
      get: "/api/document"
    };
  }
  rpc GetDocument(GetDocumentRequest) returns (GetDocumentResponse) {
    option (google.api.http) = {
      get: "/api/document/{id}"
    };
  }
  rpc DeleteDocument(DeleteDocumentRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/document/{id}"
    };
  }
  rpc UpdateDocument(UpdateDocumentRequest) returns (UpdateDocumentResponse) {
    option (google.api.http) = {
      patch: "/api/document/{document_id}"
      body: "*"
    };
  }
  rpc CreateInviteLink(CreateInviteLinkRequest) returns (CreateInviteLinkResponse) {
    option (google.api.http) = {
      post: "/api/document/{document_id}/invite"
      body: "*"
    };
  }
  rpc AcceptInvite(AcceptInviteRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/document/invite/accept"
      body: "*"
    };
  }
  rpc SetUserRole(SetUserRoleRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/document/{document_id}/role"
      body: "*"
    };
  }
  rpc RevokeAccess(RevokeAccessRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/document/{document_id}/revoke"
      body: "*"
    };
  }
}
