name: Sync to GitVerse

on:
  push:
    branches:
      - '**'  # слушает все ветки, включая feature/*, bugfix/* и т.д.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Push to GitVerse
        env:
          GITVERSE_TOKEN: ${{ secrets.GITVERSE_TOKEN }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          git remote add gitverse https://oauth2:${GITVERSE_TOKEN}@gitverse.ru/Anabol1ks/LiveEdit.git
          git push gitverse HEAD:${BRANCH_NAME}
